### ISSUE TITLE
Setting unknown property: dosamigos\typeahead\TypeAhead::clientEvents

### ISSUE THREAD

**Issue by Mazorati** [2amigos/yii2-type-ahead-widget#11]

**Comment by loktionov** [comment]
There is a conflict between  yiisoft/yii2-gii and  2amigos/yii2-type-ahead-widget 1.1
I have an error when trying install 1.1
 Problem 1
    - Installation request for 2amigos/yii2-type-ahead-widget >=1.1 -> satisfiable by 2amigos/yii2-type-ahead-widget[1.1].
    - Conclusion: remove bower-asset/typeahead.js v0.10.5
    - yiisoft/yii2-gii 2.0.4 requires bower-asset/typeahead.js 0.10.* -> satisfiable by bower-asset/typeahead.js[v0.10.5].
    - yiisoft/yii2-gii 2.0.4 requires bower-asset/typeahead.js 0.10.* -> satisfiable by bower-asset/typeahead.js[v0.10.5].
    - yiisoft/yii2-gii 2.0.3 requires bower-asset/typeahead.js 0.10.* -> satisfiable by bower-asset/typeahead.js[v0.10.5].
    - yiisoft/yii2-gii 2.0.2 requires bower-asset/typeahead.js 0.10.* -> satisfiable by bower-asset/typeahead.js[v0.10.5].
    - yiisoft/yii2-gii 2.0.1 requires bower-asset/typeahead.js 0.10.* -> satisfiable by bower-asset/typeahead.js[v0.10.5].
    - yiisoft/yii2-gii 2.0.0 requires bower-asset/typeahead.js 0.10.* -> satisfiable by bower-asset/typeahead.js[v0.10.5].
    - Conclusion: don't install bower-asset/typeahead.js v0.10.5
    - Installation request for yiisoft/yii2-gii * -> satisfiable by yiisoft/yii2-gii[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].

**Comment by tonydspaniard** [comment]
@loktionov the problem is with gii as it uses a lower version, not with the extension.

**Comment by tonydspaniard** [comment]
@Mazorati i need more info, code sample?

**Comment by dzona** [comment]
closing issue due to lack of information
