### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by legounit** [2amigos/yii2-type-ahead-widget#6]
hi, i use widget and  i have a question about events. how  i can  specify the  events (https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#custom-events) in your widget?

**Comment by razvanphp** [comment]
+1 for this feature.

@albertodiaz I think you are using a different plugin:
https://github.com/kartik-v/yii2-widget-typeahead/blob/master/TypeaheadBasic.php#L87

**Comment by creocoder** [comment]
Fixed by #10
