### ISSUE TITLE
Bump typeahead.js bower version

### ISSUE THREAD

**Issue by razvanphp** [2amigos/yii2-type-ahead-widget#9]
Thank you for this great plugin!

Can you please bump to the composer.js to the latest version?
https://github.com/twitter/typeahead.js/releases/tag/v0.11.0

There are cool news features like the `typeahead:change` event, hopefully we can nicely define them when #6 is ready :)

**Comment by creocoder** [comment]
@razvanphp Enhanced by 1.1 release

**Comment by razvanphp** [comment]
Great! Thank you. Just a small note, the event was renamed in the new release to `typeahead:select` so you might want to update the readme in the master.
https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#custom-events
